# Generated by Django 3.2.1 on 2024-02-09 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('options', models.CharField(choices=[("A'lo", "A'lo"), ('Yaxshi', 'Yaxshi'), ('Qoniqarli', 'Qoniqarli'), ('Qoniqarsiz', 'Qoniqarsiz')], max_length=20)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteapp.vote')),
            ],
        ),
    ]
