# Generated by Django 3.2.1 on 2024-02-09 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0002_voteitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteitems',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='voteapp.professor'),
            preserve_default=False,
        ),
    ]
